version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4 # Mudamos para a imagem que tem suporte a mapas (PostGIS)
    container_name: georout-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: desafio_db
    ports:
      - "5434:5432" # <-- Mudamos a porta externa para 5434 para não dar conflito com seus outros projetos
    volumes:
      - georout_postgres_data:/var/lib/postgresql/data

volumes:
  georout_postgres_data: