spring.application.name=georout-api

# Habilitação de Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5434/desafio_db
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate / JPA (O dialeto agora é resolvido automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true